version: "3"
services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        networks:
            - webnet
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: "eth_keys"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    redis:
        image: redis
        environment:
            - REDIS_APPENDONLY=yes
            - REDIS_APPENDFSYNC=always
        volumes:
            - ./redis-data:/data
        networks:
            - webnet
    web:
        image: cyrdocker/ethereum-wallet-bot
        networks:
            - webnet
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DB_HOST: db
            REDIS_HOST: redis
            BOT_TOKEN: ${BOT_TOKEN}
            API_URL: ${API_URL}
        depends_on:
            - redis
            - db
        command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
volumes:
    pgdata:
    redis-data:
networks:
    webnet:
